[workspace]
members = [
  "crates/chain",
  "crates/config",
  "crates/common",
  "crates/generator",
  "crates/store",
  "crates/types",
  "crates/jsonrpc-types",
  "crates/setup-tool",
  "packages/aggregator/native",
]
