[package]
name = "gw-readonly-node"
version = "0.1.0"
authors = ["Nervos Network"]
edition = "2018"
autobins = false

[[bin]]
name = "gw-readonly-node"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
async-channel = "1.4.2"
async-jsonrpc-client = { version = "0.3.0", default-features = false, features = ["http-async-std"] }
async-native-tls = "0.3.3"
async-std = "1.9.0"
bytes-v10 = { version = "1.0", package = "bytes" }
clap = "2.33.3"
ctrlc = "3.1.6"
env_logger = "0.8.3"
futures = "0.3.13"
hyper = "0.14"
jsonrpc-v2 = { version = "0.10.0", default-features = false, features = ["hyper-integration", "easy-errors"] }
log = "0.4.14"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smol = "1.2.5"
sqlx = { version = "0.5", features = [ "runtime-async-std-native-tls" ] }
tokio = { version = "1.0.1", default-features = false, features = ["rt-multi-thread"] }

ckb-types = "0.37.0"
godwoken-polyjuice = "0.0.6"
gw-chain = { path = "../chain" }
gw-common = { path = "../common" }
gw-config = { path = "../config" }
gw-generator = { path = "../generator" }
gw-jsonrpc-types= { path = "../jsonrpc-types" }
gw-store = { path = "../store" }
gw-types = { path = "../types" }
